CREATE SEQUENCE IF NOT EXISTS users_seq
  START WITH 100
  INCREMENT BY 1
  NO MAXVALUE
  NO MINVALUE
  CACHE 1;

CREATE SEQUENCE IF NOT EXISTS orders_seq
  START WITH 100
  INCREMENT BY 1
  NO MAXVALUE
  NO MINVALUE
  CACHE 1;


CREATE TABLE users(
  users_id INTEGER DEFAULT nextval('users_seq'),
  name VARCHAR(100) NOT NULL,
  address VARCHAR(500) NOT NULL,
  state VARCHAR(50) NOT NULL,
  city VARCHAR(50) NOT NULL,
  pincode VARCHAR(6) NOT NULL,
  mobileno VARCHAR(10) NOT NULL,
  email VARCHAR(100) NOT NULL,
  usertype VARCHAR(50) NOT NULL,
  createddate TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (users_id)
);


CREATE TABLE orders(
  order_id INTEGER DEFAULT nextval('orders_seq'),
  moviedate DATE default CURRENT_DATE,
  bookeddate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  paid bigint NOT NULL,
  users_id INTEGER NOT NULL,
  theatreshow_id INTEGER NOT NULL,
  PRIMARY KEY (order_id),
  FOREIGN KEY (users_id) REFERENCES users (users_id)
    ON DELETE CASCADE,
  FOREIGN KEY (theatreshow_id) REFERENCES theatreshow (theatreshow_id)
    ON DELETE CASCADE
);